name: Auto PR

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    if: github.repository == 'ajohnson-va/secrel-cli'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}

      - name: Create Draft PR
        env:
          GH_TOKEN: ${{ secrets.SECREL_FGAT }}
        run: |
          # Grab branch name from create trigger
          BRANCH_NAME=${{ github.event.ref }}
          if [ "${{ github.event_name }}" == "push" ] ; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
            # Sleep in case this was called at the same time as a branch create
            sleep 10s
          fi
          # Check if PR already exists
          PR_EXISTS=$(gh pr list --json headRefName | jq --arg branch "$BRANCH_NAME" '.[] | select(.headRefName==$branch)')
          if [ -z "$PR_EXISTS" ] ; then
            BRANCH_NAME=$(echo "$BRANCH_NAME" | awk '{print tolower($0)}')
            PR_TITLE=$(echo "$BRANCH_NAME")
            gh pr create --title "$PR_TITLE" -F ./pull-request-template.md --draft --base main
          fi
