name: CI

on:
  workflow_dispatch:

  push:
    branches-ignore: [ main ]

  pull_request:
    branches: [ main ]

env:
  GH_TOKEN: ${{ github.token }}
  TEST_BRANCH: ${{ vars.TEST_BRANCH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          python -m pip install -r requirements.txt;
        fi
        
    - name: Execute tests
      run: pip install pytest && pytest -s

    - name: Install app
      run: scripts/install-app.sh

    - name: Test secrel pipeline run command
      run: secrel pipeline run -r ${{ env.TEST_BRANCH }}
