name: CI

on:
  workflow_dispatch:

  push:
    branches-ignore: [ main ]

  pull_request:
    branches: [ main ]

env:
  GH_TOKEN: ${{ secrets.SECREL_FGAT }}
  ORGANIZATION: ${{ vars.ORGANIZATION }}
  PIPELINE_REPO: ${{ vars.PIPELINE_REPO }}
  PIPELINE_WORKFLOW: ${{ vars.PIPELINE_WORKFLOW }}
  PIPELINE_E2E_TESTS: ${{ vars.PIPELINE_E2E_TESTS }}
  PIPELINE_DEFAULT_BRANCH: ${{ vars.PIPELINE_DEFAULT_BRANCH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          python -m pip install -r requirements.txt;
        fi

    - name: Install app
      run: scripts/install-app.sh

    - name: Test app installation
      run: secrel pipeline run

    - name: Execute tests
      run: pip install pytest && pytest
